name: henri_potier_riverpod
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.3
  dio: ^5.3.3
  equatable: ^2.0.5
  riverpod: ^2.4.3
  flutter_riverpod: ^2.4.3
  get_it: ^7.6.4
  go_router: ^11.1.4
  shimmer: ^3.0.0
  nock: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  mockito: ^5.4.2


flutter:
  uses-material-design: true


  assets:     
    - assets/harry.jpg